### PR TITLE
[EPLT-997] Optionally show pass and second input for confirmation

### PR DESCRIPTION
**Pull request by oriahu**
Password not required

Screen Shot 2020-01-03 at 3 28 49 PM

Password required

Screen Shot 2020-01-03 at 3 29 33 PM

### CODE REVIEW

**Comment by oriahu** [comment]
How about a checkbox instead of an :eye: Was thinking it would be neat but now realizing it kinda stands out too much. a simple checkr-blue check in a box would be great.

**Review by sesquipedalian-dev — COMMENTED** [review]
Not necessarily due to changes here, but I'd like to see some changes to the interface here.  

One small thing that was weird - when you change the number of invalidity messages for the password, the panel is growing 'up' instead of 'down'? see attached [video](https://drive.google.com/open?id=1L2q2SmK-qKvRFnFCfORHPd2jOSQ5fdXH)

Here's an image showing what else I would change
sendr password box write up

**Comment by sesquipedalian-dev** [comment]
Great fix for the width of the password entry fields. 

- can you move the 'Show Password' stuff below the password and confirmation inputs? I think it draws too much attention since it should be  optional to use it
- the 'eye' checkbox looks bad. It should be a white image with blue background like the 'lock' button for requiring password (when PASSWORD_REQUIRED=false).  Or it could be a checkbox with the same motif, etc.  Right now it's a black image on blue background and not very readable.

**Comment by charli-watson** [comment]
Agree with Scott, can we make these match? I'd go with white image on blue background:
image

Also where is the eye icon from?

**Comment by oriahu** [comment]
> Also where is the eye icon from?

Creative commons off internet. Wondering if there is an icon in the same set the lock came from

**Comment by charli-watson** [comment]
> Creative commons off internet. Wondering if there is an icon in the same set the lock came from

Ok cool, I think it's fine if it's not from the same set for now.

**Comment by oriahu** [comment]
Created one from a black checkmark: 
Screen Shot 2020-01-03 at 3 22 13 PM

**Review by sesquipedalian-dev — APPROVED** [review]
looks good

**Comment by charli-watson** [comment]
`.hidden` should get rid of the extra space here:

image


Otherwise looks good!

**Pull request merged**
